# wrangler.toml
name = 'ailodi-blog'
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[env.production]
name = "ailodi-blog-production"

[env.preview]
name = "ailodi-blog-preview"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables for build
[vars]
NODE_ENV = "production"